# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-19 11:09
from __future__ import unicode_literals

from django.db import migrations
import norman.models.user


class Migration(migrations.Migration):

    dependencies = [
        ('norman', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', norman.models.user.CustomUserManager()),
            ],
        ),
    ]
